version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/giddh-node-pdf

permissions:
  - object: /
     pattern: "**"
     owner: root
     group: root

hooks:
  AfterInstall:
   - location: /home/ec2-user/install-pkgs.sh
     timeout: 1200
     runas: root

  ApplicationStart:
   - location: /home/ec2-user/app-start.sh
     timeout: 60
     runas: root
