version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/giddh-node-pdf

hooks:
  AfterInstall:
   - location: install-pkgs
     timeout: 1200
     runas: root

  ApplicationStart:
   - location: app-start
     timeout: 120
     runas: root
