version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/giddh-node-pdf

hooks:
  AfterInstall:
   - location: codedeploy/install-pkgs.sh
     timeout: 1200
     runas: root

  ApplicationStart:
   - location: codedeploy/app-start.sh
     timeout: 120
     runas: root
