module.exports = {
    "introspectionCache": {},
    "templateNameStack": [],
    "macroNameStack": [],
    "eventCartridge": null,
    "currentResource": null,
    "macroLibraries": null,
    "innerContext": null,
    "context": {
        "companyName": "Mustafa SN Corp",
        "dueDate": "07-06-2019",
        "taxes": [{
            "amount": 5.55,
            "taxRate": 5.0,
            "accountUniqueName": "igstgstat5",
            "accountName": "IGST (GST at 5%)",
            "visibleTaxRate": 5.0,
            "hasError": false,
            "errorMessage": ""
        }],
        "gstin": "238789789789798",
        "gstEntriesTotal": 116.55,
        "totalTax": 5.55,
        "thanks": "",
        "minHeight": "940.0px",
        "total": 117.00,
        "balance": 117.00,
        "companyEmail": "some@gmail.com",
        "rightMargin": "10.0px",
        "secondryColor": "#dF4927",
        "totalInWords": "One Hundred Seventeen Only",
        "invoiceNumber": "20180418-21",
        "pirmaryColor": "#dF4927",
        "pan": "ARLPA0061H",
        "taxableAmount": 111.00,
        "margin": "true",
        "leftMargin": "10.0px",
        "grandTotal": 117.00,
        "billingState": "Jammu and Kashmir",
        "label": {
            "formNameInvoice": false,
            "date": "Date",
            "taxableAmount": "Taxable Amount",
            "item": "Item",
            "grandTotal": "Invoice Total",
            "companyName": "",
            "dueDate": "Due Date",
            "description": "Some label",
            "taxes": "taxes",
            "billingState": "State",
            "gstin": "GSTIN",
            "invoiceDate": "Invoice Date",
            "customerName": "",
            "totalTax": "Total Tax*",
            "total": "total",
            "formNameTaxInvoice": "TAX INVOICE",
            "sNo": "S no.",
            "taxableValue": "Taxable Value",
            "totalInWords": "Invoice Total (In words)",
            "invoiceNumber": "Invoice No.",
            "shippingAddress": "Shipping Address",
            "shippingState": "State",
            "billingAddress": "Billing Address",
            "pan": "PAN"
        },
        "invoiceDate": "18-04-2018",
        "customerName": "cashaccount",
        "showlogo": false,
        "entries": [{
            "uniqueName": "aro1532003240259",
            "discounts": [],
            "taxes": [{
                "rate": 5.00,
                "accountName": "IGST",
                "accountUniqueName": "igst",
                "amount": 5.55,
                "type": "DEBIT"
            }],
            "transactions": [{
                "accountName": "Sales",
                "accountUniqueName": "sales",
                "type": "DEBIT",
                "amount": 111.00,
                "hsnNumber": null,
                "sacNumber": null,
                "description": "",
                "quantity": null,
                "stockUnit": "",
                "category": "income",
                "taxableValue": 111.00,
                "date": null,
                "isStockTxn": null,
                "stockDetails": {
                    "name": null,
                    "uniqueName": null
                },
                "rate": null
            }, {
                "accountName": "Mustafa",
                "accountUniqueName": "mustafa",
                "type": "DEBIT",
                "amount": 111.00,
                "hsnNumber": null,
                "sacNumber": null,
                "description": "",
                "quantity": null,
                "stockUnit": "",
                "category": "income",
                "taxableValue": 111.00,
                "date": null,
                "isStockTxn": null,
                "stockDetails": {
                    "name": null,
                    "uniqueName": null
                },
                "rate": null
            }],
            "description": "",
            "taxableValue": 111.00,
            "discountTotal": 0,
            "nonTaxableValue": 0,
            "entryDate": "18-04-2018",
            "taxList": [],
            "voucherType": null,
            "entryTotal": 116.55
        }, {
            "uniqueName": "aro1532003240259",
            "discounts": [],
            "taxes": [{
                "rate": 5.00,
                "accountName": "IGST",
                "accountUniqueName": "igst",
                "amount": 5.55,
                "type": "DEBIT"
            }],
            "transactions": [{
                "accountName": "Sales",
                "accountUniqueName": "sales",
                "type": "DEBIT",
                "amount": 111.00,
                "hsnNumber": null,
                "sacNumber": null,
                "description": "",
                "quantity": null,
                "stockUnit": "",
                "category": "income",
                "taxableValue": 111.00,
                "date": null,
                "isStockTxn": null,
                "stockDetails": {
                    "name": null,
                    "uniqueName": null
                },
                "rate": null
            }],
            "description": "",
            "taxableValue": 111.00,
            "discountTotal": 0,
            "nonTaxableValue": 0,
            "entryDate": "18-04-2018",
            "taxList": [],
            "voucherType": null,
            "entryTotal": 116.55
        }, {
            "uniqueName": "aro1532003240259",
            "discounts": [],
            "taxes": [{
                "rate": 5.00,
                "accountName": "IGST",
                "accountUniqueName": "igst",
                "amount": 5.55,
                "type": "DEBIT"
            }],
            "transactions": [{
                "accountName": "Sales",
                "accountUniqueName": "sales",
                "type": "DEBIT",
                "amount": 111.00,
                "hsnNumber": null,
                "sacNumber": null,
                "description": "",
                "quantity": null,
                "stockUnit": "",
                "category": "income",
                "taxableValue": 111.00,
                "date": null,
                "isStockTxn": null,
                "stockDetails": {
                    "name": null,
                    "uniqueName": null
                },
                "rate": null
            }],
            "description": "",
            "taxableValue": 111.00,
            "discountTotal": 0,
            "nonTaxableValue": 0,
            "entryDate": "18-04-2018",
            "taxList": [],
            "voucherType": null,
            "entryTotal": 116.55
        }, {
            "uniqueName": "aro1532003240259",
            "discounts": [],
            "taxes": [{
                "rate": 5.00,
                "accountName": "IGST",
                "accountUniqueName": "igst",
                "amount": 5.55,
                "type": "DEBIT"
            }],
            "transactions": [{
                "accountName": "Sales",
                "accountUniqueName": "sales",
                "type": "DEBIT",
                "amount": 111.00,
                "hsnNumber": null,
                "sacNumber": null,
                "description": "",
                "quantity": null,
                "stockUnit": "",
                "category": "income",
                "taxableValue": 111.00,
                "date": null,
                "isStockTxn": null,
                "stockDetails": {
                    "name": null,
                    "uniqueName": null
                },
                "rate": null
            }],
            "description": "",
            "taxableValue": 111.00,
            "discountTotal": 0,
            "nonTaxableValue": 0,
            "entryDate": "18-04-2018",
            "taxList": [],
            "voucherType": null,
            "entryTotal": 116.55
        }],
        "gstTaxesTotal": [{
            "total": 5.55,
            "uniqueName": "igst",
            "name": "IGST"
        }],
        "topMargin": "10.0px",
        "bottomMargin": "10.0px",
        "companyAddress": "",
        "companyMobileNo": "9199773812",
        "shippingAddress": [],
        "shippingState": "Jammu and Kashmir",
        "billingAddress": [],
        "taxableTotal": 111.00,
        "roundOff": "0.45",
        "slogan": "New SN Corp",
        "paidAmount": 0.00,
        "message1": "Facebook",
        "font": "open sans"
    },
    "chainedContext": null,
    "keys": ["companyName", "dueDate", "taxes", "gstin", "gstEntriesTotal", "totalTax", "thanks", "minHeight", "total", "balance", "companyEmail", "rightMargin", "secondryColor", "totalInWords", "invoiceNumber", "pirmaryColor", "pan", "taxableAmount", "margin", "leftMargin", "grandTotal", "billingState", "label", "invoiceDate", "customerName", "showlogo", "entries", "gstTaxesTotal", "topMargin", "bottomMargin", "companyAddress", "companyMobileNo", "shippingAddress", "shippingState", "billingAddress", "taxableTotal", "roundOff", "slogan", "paidAmount", "message1", "font"],
    "currentTemplateName": "<undef>",
    "currentMacroName": "<undef>",
    "currentMacroCallDepth": 0
}