// module.exports = {
//     "introspectionCache": {},
//     "templateNameStack": [],
//     "macroNameStack": [],
//     "eventCartridge": null,
//     "currentResource": null,
//     "macroLibraries": null,
//     "innerContext": null,
//     "context": {
//         "dueDateYear": null,
//         "companyName": "Walkover Web Solutions PVT LTD",
//         "invoiceDateInt": "09",
//         "taxes": [],
//         "totalTax": 0.00,
//         "thanks": "",
//         // "minHeight": "940.0px",
//         "balance": 290.00,
//         "secondryColor": "#dF4927",
//         "totalInWords": "Two Hundred Ninety Only",
//         "customerEmail": "4y0fg6yptnz7v42@marketplace.amazon.in",
//         "mapOfTaxes": [],
//         "margin": "true",
//         "grandTotal": 290.00,
//         "billingState": "Kerala",
//         "customerName": "Akhil S. Panicker",
//         "entries": [
//             {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": 12,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": 33,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": 12
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": 33
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": 66
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": 123,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": 234,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "rse1531139207418",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Shipping price",
//                     "accountUniqueName": "shippingprice",
//                     "type": "DEBIT",
//                     "amount": 40.18,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "income",
//                     "taxableValue": 40.18,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Shipping price",
//                 "taxableValue": 40.18,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 40.18
//             }, {
//                 "uniqueName": "y0u1531139207571",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "Gift Wrap Price",
//                     "accountUniqueName": "giftwrapprice",
//                     "type": "DEBIT",
//                     "amount": 0.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "",
//                     "quantity": null,
//                     "stockUnit": "",
//                     "category": "other",
//                     "taxableValue": null,
//                     "date": null,
//                     "isStockTxn": null,
//                     "stockDetails": {
//                         "name": null,
//                         "uniqueName": null
//                     },
//                     "rate": null
//                 }],
//                 "description": "Gift Wrap Price",
//                 "taxableValue": 0.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0.00,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 0.00
//             }, {
//                 "uniqueName": "c6p1531139207672",
//                 "discounts": [],
//                 "taxes": [],
//                 "transactions": [{
//                     "accountName": "SALES",
//                     "accountUniqueName": "sales",
//                     "type": "DEBIT",
//                     "amount": 250.00,
//                     "hsnNumber": null,
//                     "sacNumber": null,
//                     "description": "FashionFrame Handmade Wooden Pocket Cigarette Case Holder",
//                     "quantity": 1.00,
//                     "stockUnit": "nos",
//                     "category": "income",
//                     "taxableValue": 250.00,
//                     "date": null,
//                     "isStockTxn": true,
//                     "stockDetails": {
//                         "name": "FashionFrame Handmade Wooden Pocket Cigarette Case Holder",
//                         "uniqueName": "fashionframehandmadewoodenpocketcigarettecaseholder"
//                     },
//                     "rate": 250.00
//                 }],
//                 "description": "",
//                 "taxableValue": 250.00,
//                 "discountTotal": 0,
//                 "nonTaxableValue": 0,
//                 "entryDate": "09-07-2018",
//                 "taxList": [],
//                 "voucherType": null,
//                 "entryTotal": 250.00
//             }
//         ],
//         "topMargin": "10.0px",
//         "logopath": "https://d1qb2nb5cznatu.cloudfront.net/startups/i/149029-007ec86f42919835fa589669ea04c9e6-medium_jpg.jpg",
//         "bottomMargin": "10.0px",
//         "shippingState": "Kerala",
//         "sumOfTaxes": [],
//         "taxableTotal": 290.18,
//         "slogan": "Hello slogan",
//         "paidAmount": 0.00,
//         "dueDateInt": null,
//         "gstin": "242323232323232",
//         "gstEntriesTotal": 290.18,
//         "invoiceDateMonth": "July",
//         "total": 290.00,
//         "companyEmail": "info@hubspace.in",
//         "rightMargin": "10.0px",
//         "invoiceNumber": "20180709-872",
//         "currency": "INR",
//         "pirmaryColor": "#dF4927",
//         "dueDateMonth": null,
//         "taxableAmount": 290.18,
//         "showSplittedDate": true,
//         "leftMargin": "10.0px",
//         "manageInventory": true,
//         "label": {
//             "hsnSac": "hsnSac",
//             "date": "Date",
//             "companyName": "",
//             "description": "Some label",
//             "taxes": true,
//             "gstin": "GSTIN",
//             "pan": "PAN",
//             "totalTax": "Total Tax*",
//             "total": "Total",
//             "sNo": "S. No.",
//             "rate": "Rate/ Item",
//             "totalInWords": "Invoice Total (In words)",
//             "customerEmail": "",
//             "invoiceNumber": "Invoice No.",
//             "formNameInvoice": "INVOICE",
//             "taxableAmount": "Sub Total",
//             "item": "Descripion",
//             "quantity": "Qty.",
//             "grandTotal": "Invoice Total",
//             "billingState": "State",
//             "invoiceDate": "Invoice Date",
//             "customerName": "",
//             "formNameTaxInvoice": "TAX INVOICE 1",
//             "taxableValue": "Taxable Amt.",
//             "companyAddress": "",
//             "shippingAddress": "Shipping Address",
//             "shippingState": "State",
//             "billingAddress": "Billing Address"
//         },
//         "invoiceDate": "09-07-2018",
//         "showDueDate": true,
//         "showlogo": true,
//         "gstTaxesTotal": [],
//         "companyAddress": "Address 121212",
//         "companyMobileNo": null,
//         "shippingAddress": ["Geeta Monitors 1st Floor, Gym Complex,near Pullepady Bridge"],
//         "invoiceDateYear": "2018",
//         "billingAddress": ["Geeta Monitors 1st Floor, Gym Complex,near Pullepady Bridge"],
//         "roundOff": "- 0.18",
//         "message1": "",
//         "font": "open sans"
//     },
//     "keys": ["dueDateYear", "companyName", "invoiceDateInt", "taxes", "totalTax", "thanks", "minHeight", "balance", "secondryColor", "totalInWords", "customerEmail", "mapOfTaxes", "margin", "grandTotal", "billingState", "customerName", "entries", "topMargin", "logopath", "bottomMargin", "shippingState", "sumOfTaxes", "taxableTotal", "slogan", "paidAmount", "dueDateInt", "gstin", "gstEntriesTotal", "invoiceDateMonth", "total", "companyEmail", "rightMargin", "invoiceNumber", "currency", "pirmaryColor", "dueDateMonth", "taxableAmount", "showSplittedDate", "leftMargin", "manageInventory", "label", "invoiceDate", "showDueDate", "showlogo", "gstTaxesTotal", "companyAddress", "companyMobileNo", "shippingAddress", "invoiceDateYear", "billingAddress", "roundOff", "message1", "font"],
//     "chainedContext": null,
//     "currentTemplateName": "<undef>",
//     "currentMacroName": "<undef>",
//     "currentMacroCallDepth": 0
// }

module.exports = {
	"introspectionCache": {},
	"templateNameStack": [],
	"macroNameStack": [],
	"eventCartridge": null,
	"currentResource": null,
	"macroLibraries": null,
	"innerContext": null,
	"context": {
		"companyName": "New SN Corp",
		"dueDate": "07-06-2019",
		"taxes": [{
			"amount": 5.55,
			"taxRate": 5.0,
			"accountUniqueName": "igstgstat5",
			"accountName": "IGST (GST at 5%)",
			"visibleTaxRate": 5.0,
			"hasError": false,
			"errorMessage": ""
		}],
		"gstin": "238789789789798",
		"gstEntriesTotal": 116.55,
		"totalTax": 5.55,
		"thanks": "",
		"minHeight": "940.0px",
		"total": 117.00,
		"balance": 117.00,
		"companyEmail": "some@gmail.com",
		"rightMargin": "10.0px",
		"secondryColor": "#dF4927",
		"totalInWords": "One Hundred Seventeen Only",
		"invoiceNumber": "20180418-21",
		"pirmaryColor": "#dF4927",
		"pan": "ARLPA0061H",
		"taxableAmount": 111.00,
		"margin": "true",
		"leftMargin": "10.0px",
		"grandTotal": 117.00,
		"billingState": "Jammu and Kashmir",
		"label": {
			"formNameInvoice": false,
			"date": "Date",
			"taxableAmount": "Taxable Amount",
			"item": "Item",
			"grandTotal": "Invoice Total",
			"companyName": "",
			"dueDate": "Due Date",
			"description": "Some label",
			"taxes": "taxes",
			"billingState": "State",
			"gstin": "GSTIN",
			"invoiceDate": "Invoice Date",
			"customerName": "",
			"totalTax": "Total Tax*",
			"total": "total",
			"formNameTaxInvoice": "TAX INVOICE",
			"sNo": "S no.",
			"taxableValue": "Taxable Value",
			"totalInWords": "Invoice Total (In words)",
			"invoiceNumber": "Invoice No.",
			"shippingAddress": "Shipping Address",
			"shippingState": "State",
			"billingAddress": "Billing Address",
			"pan": "PAN"
		},
		"invoiceDate": "18-04-2018",
		"customerName": "cashaccount",
		"showlogo": false,
		"entries": [{
			"uniqueName": "aro1532003240259",
			"discounts": [],
			"taxes": [{
				"rate": 5.00,
				"accountName": "IGST",
				"accountUniqueName": "igst",
				"amount": 5.55,
				"type": "DEBIT"
			}],
			"transactions": [{
				"accountName": "Sales",
				"accountUniqueName": "sales",
				"type": "DEBIT",
				"amount": 111.00,
				"hsnNumber": null,
				"sacNumber": null,
				"description": "",
				"quantity": null,
				"stockUnit": "",
				"category": "income",
				"taxableValue": 111.00,
				"date": null,
				"isStockTxn": null,
				"stockDetails": {
					"name": null,
					"uniqueName": null
				},
				"rate": null
			}],
			"description": "",
			"taxableValue": 111.00,
			"discountTotal": 0,
			"nonTaxableValue": 0,
			"entryDate": "18-04-2018",
			"taxList": [],
			"voucherType": null,
			"entryTotal": 116.55
		}],
		"gstTaxesTotal": [{
			"total": 5.55,
			"uniqueName": "igst",
			"name": "IGST"
		}],
		"topMargin": "10.0px",
		"bottomMargin": "10.0px",
		"companyAddress": "",
		"companyMobileNo": "9199773812",
		"shippingAddress": [],
		"shippingState": "Jammu and Kashmir",
		"billingAddress": [],
		"taxableTotal": 111.00,
		"roundOff": "0.45",
		"slogan": "New SN Corp",
		"paidAmount": 0.00,
		"message1": "Facebook",
		"font": "open sans"
	},
	"chainedContext": null,
	"keys": ["companyName", "dueDate", "taxes", "gstin", "gstEntriesTotal", "totalTax", "thanks", "minHeight", "total", "balance", "companyEmail", "rightMargin", "secondryColor", "totalInWords", "invoiceNumber", "pirmaryColor", "pan", "taxableAmount", "margin", "leftMargin", "grandTotal", "billingState", "label", "invoiceDate", "customerName", "showlogo", "entries", "gstTaxesTotal", "topMargin", "bottomMargin", "companyAddress", "companyMobileNo", "shippingAddress", "shippingState", "billingAddress", "taxableTotal", "roundOff", "slogan", "paidAmount", "message1", "font"],
	"currentTemplateName": "<undef>",
	"currentMacroName": "<undef>",
	"currentMacroCallDepth": 0
}