module.exports = {
    "introspectionCache": {},
    "templateNameStack": [],
    "macroNameStack": [],
    "eventCartridge": null,
    "currentResource": null,
    "macroLibraries": null,
    "innerContext": null,
    "context": {
        "dueDateYear": null,
        "companyName": "Walkover Web Solutions PVT LTD",
        "invoiceDateInt": "09",
        "taxes": [],
        "totalTax": 0.00,
        "thanks": "",
        // "minHeight": "940.0px",
        "balance": 290.00,
        "secondryColor": "#dF4927",
        "totalInWords": "Two Hundred Ninety Only",
        "customerEmail": "4y0fg6yptnz7v42@marketplace.amazon.in",
        "mapOfTaxes": [],
        "margin": "true",
        "grandTotal": 290.00,
        "billingState": "Kerala",
        "customerName": "Akhil S. Panicker",
        "entries": [
            {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": 12,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": 33,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": 12
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": 33
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": 66
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": 123,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": 234,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "rse1531139207418",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Shipping price",
                    "accountUniqueName": "shippingprice",
                    "type": "DEBIT",
                    "amount": 40.18,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "income",
                    "taxableValue": 40.18,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Shipping price",
                "taxableValue": 40.18,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 40.18
            }, {
                "uniqueName": "y0u1531139207571",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "Gift Wrap Price",
                    "accountUniqueName": "giftwrapprice",
                    "type": "DEBIT",
                    "amount": 0.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "",
                    "quantity": null,
                    "stockUnit": "",
                    "category": "other",
                    "taxableValue": null,
                    "date": null,
                    "isStockTxn": null,
                    "stockDetails": {
                        "name": null,
                        "uniqueName": null
                    },
                    "rate": null
                }],
                "description": "Gift Wrap Price",
                "taxableValue": 0.00,
                "discountTotal": 0,
                "nonTaxableValue": 0.00,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 0.00
            }, {
                "uniqueName": "c6p1531139207672",
                "discounts": [],
                "taxes": [],
                "transactions": [{
                    "accountName": "SALES",
                    "accountUniqueName": "sales",
                    "type": "DEBIT",
                    "amount": 250.00,
                    "hsnNumber": null,
                    "sacNumber": null,
                    "description": "FashionFrame Handmade Wooden Pocket Cigarette Case Holder",
                    "quantity": 1.00,
                    "stockUnit": "nos",
                    "category": "income",
                    "taxableValue": 250.00,
                    "date": null,
                    "isStockTxn": true,
                    "stockDetails": {
                        "name": "FashionFrame Handmade Wooden Pocket Cigarette Case Holder",
                        "uniqueName": "fashionframehandmadewoodenpocketcigarettecaseholder"
                    },
                    "rate": 250.00
                }],
                "description": "",
                "taxableValue": 250.00,
                "discountTotal": 0,
                "nonTaxableValue": 0,
                "entryDate": "09-07-2018",
                "taxList": [],
                "voucherType": null,
                "entryTotal": 250.00
            }
        ],
        "topMargin": "10.0px",
        "logopath": "https://d1qb2nb5cznatu.cloudfront.net/startups/i/149029-007ec86f42919835fa589669ea04c9e6-medium_jpg.jpg",
        "bottomMargin": "10.0px",
        "shippingState": "Kerala",
        "sumOfTaxes": [],
        "taxableTotal": 290.18,
        "slogan": "Hello slogan",
        "paidAmount": 0.00,
        "dueDateInt": null,
        "gstin": "242323232323232",
        "gstEntriesTotal": 290.18,
        "invoiceDateMonth": "July",
        "total": 290.00,
        "companyEmail": "info@hubspace.in",
        "rightMargin": "10.0px",
        "invoiceNumber": "20180709-872",
        "currency": "INR",
        "pirmaryColor": "#dF4927",
        "dueDateMonth": null,
        "taxableAmount": 290.18,
        "showSplittedDate": true,
        "leftMargin": "10.0px",
        "manageInventory": true,
        "label": {
            "hsnSac": "hsnSac",
            "date": "Date",
            "companyName": "",
            "description": "Some label",
            "taxes": false,
            "gstin": "GSTIN",
            "pan": "PAN",
            "totalTax": "Total Tax*",
            "total": "Total",
            "sNo": "S. No.",
            "rate": "Rate/ Item",
            "totalInWords": "Invoice Total (In words)",
            "customerEmail": "",
            "invoiceNumber": "Invoice No.",
            "formNameInvoice": "INVOICE",
            "taxableAmount": "Sub Total",
            "item": "Descripion",
            "quantity": "Qty.",
            "grandTotal": "Invoice Total",
            "billingState": "State",
            "invoiceDate": "Invoice Date",
            "customerName": "",
            "formNameTaxInvoice": "TAX INVOICE 1",
            "taxableValue": "Taxable Amt.",
            "companyAddress": "",
            "shippingAddress": "Shipping Address",
            "shippingState": "State",
            "billingAddress": "Billing Address"
        },
        "invoiceDate": "09-07-2018",
        "showDueDate": true,
        "showlogo": true,
        "gstTaxesTotal": [],
        "companyAddress": "Address 121212",
        "companyMobileNo": null,
        "shippingAddress": ["Geeta Monitors 1st Floor, Gym Complex,near Pullepady Bridge"],
        "invoiceDateYear": "2018",
        "billingAddress": ["Geeta Monitors 1st Floor, Gym Complex,near Pullepady Bridge"],
        "roundOff": "- 0.18",
        "message1": "",
        "font": "open sans"
    },
    "keys": ["dueDateYear", "companyName", "invoiceDateInt", "taxes", "totalTax", "thanks", "minHeight", "balance", "secondryColor", "totalInWords", "customerEmail", "mapOfTaxes", "margin", "grandTotal", "billingState", "customerName", "entries", "topMargin", "logopath", "bottomMargin", "shippingState", "sumOfTaxes", "taxableTotal", "slogan", "paidAmount", "dueDateInt", "gstin", "gstEntriesTotal", "invoiceDateMonth", "total", "companyEmail", "rightMargin", "invoiceNumber", "currency", "pirmaryColor", "dueDateMonth", "taxableAmount", "showSplittedDate", "leftMargin", "manageInventory", "label", "invoiceDate", "showDueDate", "showlogo", "gstTaxesTotal", "companyAddress", "companyMobileNo", "shippingAddress", "invoiceDateYear", "billingAddress", "roundOff", "message1", "font"],
    "chainedContext": null,
    "currentTemplateName": "<undef>",
    "currentMacroName": "<undef>",
    "currentMacroCallDepth": 0
}